//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        public Book()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        [Key]
        public int ID { get; set; }
        [Required]
        [Display(Name="Название книги")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Автор")]
        public string Author { get; set; }
        [Required]
        [Range(1,int.MaxValue)]
        [Display(Name = "Цена")]
        public int Price { get; set; }
        [Display(Name = "Жанр")]
        public string Genre { get; set; }
        [Range(1,int.MaxValue)]
        [Display(Name = "Количество страниц")]
        public Nullable<int> PagesCount { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
