//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Condition {
        public Condition() {
            this.Orders = new HashSet<Order>();
        }

        [Key]
        public int ID { get; set; }
        [Display(Name = "Состояние")]
        public string Name { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}
