//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderItem {
        [Key]
        public int ID { get; set; }
        public int BookID { get; set; }
        public int OrderID { get; set; }
        public int Count { get; set; }

        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
